# my global config
global:
  scrape_interval: 10s 
  evaluation_interval: 30s # default: 1m

scrape_configs:
  - job_name: prometheus
    metrics_path: '/user-ws/actuator/prometheus'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["172.17.0.1:8080"]
  - job_name: tomtom-traffic
    metrics_path: '/prometheus'
    static_configs:
      - targets: ["172.17.0.1:8000"]
  - job_name: nifi
    static_configs:
      - targets: ["172.17.0.1:9092"]
